name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: southamerica-east1
  SERVICE_NAME: evolution-download-media

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker southamerica-east1-docker.pkg.dev --quiet

      - name: Build and Push Container
        run: |-
          docker build -t southamerica-east1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:${{ github.sha }} .
          docker push southamerica-east1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: southamerica-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          timeout: 600s
          env_vars: |
            AWS_REGION=sa-east-1
            S3_BUCKET=${{ secrets.S3_BUCKET }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            CORS_ORIGINS=*
            LOG_LEVEL=info
            SIGNED_URL_EXPIRE=3600
          flags: |
            --port=3000
            --allow-unauthenticated
            --memory=512Mi
            --cpu=1
            --min-instances=0
            --max-instances=5
            --concurrency=80
            --cpu-throttling
      - name: Map Custom Domain
        run: |-
          gcloud run domain-mappings create \
            --service=${{ env.SERVICE_NAME }} \
            --domain=${{ secrets.GCP_DOMAIN }} \
            --region=${{ env.REGION }} \
            --force-override            